import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import axios from "axios";
import { useRouter } from "next/router";

export default function Home() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const router = useRouter();

  const handleLogin = async (e) => {
    e.preventDefault();

    try {
      //requisição GET API
      const response = await axios.get("http://localhost:8080/api/users");
      const users = response.data; // Lista de Users

      //usa o find para olhar no bc e validar o username e a password inserida 
      const user = users.find(
        (user) => user.username === username && user.password === password
      );

      if (user) {
        //so adm entra
        if (user.level === "admin") {
          // Redirecionar para a página admin
          router.push("/admin");
        } else {
          setError("Acesso negado: Sem permissão para acessar o Admin.");
        }
      } else {
        setError("Credenciais inválidas. Verifique Usuário e Senha.");
      }
    } catch (err) {
      //catch error da requisição
      setError("Falha com o servidor.");
    }
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <form onSubmit={handleLogin}>
          <div className="d-flex justify-content-center p-2">
            <div className="col-md-4">
              <div>
                <h2>Login</h2>
              </div>
              <div className="form-group">
                <label className="form-label" htmlFor="username">
                  Usuário
                </label>
                <input
                  type="text"
                  id="username"
                  name="username"
                  className="form-control"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  required
                />
              </div>
              <div className="form-group">
                <label className="form-label" htmlFor="password">
                  Senha
                </label>
                <input
                  type="password"
                  id="password"
                  name="password"
                  className="form-control"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>
              <div className="form-group p-2">
                <button className="btn btn-outline-success" type="submit">
                  Login
                </button>
                <Link className="btn btn-outline-info" href="/">
                  Voltar
                </Link>
              </div>
              {error && <p style={{ color: "red" }}>{error}</p>}
            </div>
          </div>
        </form>
      </div>
    </>
  );
}