import Axios from 'axios'
import NavAdmin from '@/components/NavAdmin'
import ProfessionalAction from '@/components/ProfessionalAction'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import MenuUsers from '@/components/MenuUsers'

export default function professionals() {

  const API_URL = "http://localhost:8080/api/professionals"
  
  const [professionals, setProfissionais] = useState([]); 
  
  useEffect(() => {
    const getAllProfissionais = async () => {
      try {
        const response = await Axios.get(API_URL);
        setProfissionais(response.data);
      } catch (error) {
        console.error('Erro ao buscar os profissionais:', error);
      }
    };

    getAllProfissionais();

  }, []);

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuUsers />
      </div>

  
      <div className="d-flex justify-content-center p-2">
        <div className="container">
        <div className="row border-bottom">
        <h3> Lista de Profissioanis </h3>
        
        <table className="table table-hover">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Pais</th>
            <th scope="col">Especialidade</th>
            </tr>
        </thead>
        <tbody>

        {professionals.map(professional => (
            <tr key={professional._id}>
              <th scope="row">{professional._id}</th>
              <td>{professional.name}</td>
              <td>{professional.specialty}</td>
              <td>
                <ProfessionalAction pid={ professional._id }></ProfessionalAction>
              </td>
            </tr>
        ))}

        </tbody>
        </table>
        </div>
        </div>
      </div>  
  </>
  )
}
