import NavAdmin from '@/components/NavAdmin'
import MenuUsers from '@/components/MenuUsers';
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react';
import Axios from 'axios';
import { useRouter } from 'next/router';

export default function deleteProfessional() {
  
  const API_URL = "http://localhost:8080/api/professionals/id/";

  const [professional, setProfessional] = useState({
    name: "",
    specialty: "",
    contact: "",
    phone_number: "",
    status: "",
    created_at: ""
  });

  const router = useRouter();
  const [pid] = useState(router.query.pid); // Obtenção do ID (pid) diretamente da URL

  const [message, setMessage] = useState({ message: "", status: "" });
  const [isDeleted, setIsDeleted] = useState(false); // Novo estado para controlar a deleção

  const optionsStatus = [
    { value: '', text: '-- Selecione um estado --' },
    { value: 'true', text: 'Ativo' },
    { value: 'false', text: 'Inativo' },
  ];

  // Carregar os dados do profissional
  useEffect(() => {
    if (!pid) return;  // Evitar requisição se o pid não estiver disponível

    const getProfessional = async () => {
      try {
        const response = await Axios.get(API_URL + pid);
        setMessage({ message: "Professional carregado com sucesso! ", status: "ok" });
        setProfessional(response.data); // Atualiza o estado com os dados do profissional
      } catch (error) {
        console.error('Erro ao buscar o profissional:', error);
        setMessage({ message: "Erro ao buscar o Professional! ", status: "error" });
      }
    };

    getProfessional();

  }, [pid]);

  // Função para deletar o profissional
  const handleDeleteProfessional = async () => {
    if (isDeleted) return; // Evita chamada de deleção se o profissional já foi deletado

    try {
      const response = await Axios.delete(API_URL + pid);
      setMessage({ message: "Profissional deletado com sucesso! ", status: "ok" });
      setIsDeleted(true); // Marca o profissional como deletado
    } catch (error) {
      console.error('Erro ao deletar o Profissional:', error);
      setMessage({ message: "Erro ao deletar o Profissional! ", status: "error" });
    }
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuUsers />
        {
          message.status === "" ? "" :
            message.status === "ok" ? 
              <div className='alert alert-success' role='alert'>
                {message.message}
                <Link className='alert-link' href='/admin/professionals'>Voltar</Link>
              </div> : 
              <div className='alert alert-danger' role='alert'>
                {message.message}
                <Link className='alert-link' href='/admin/professionals'>Voltar</Link>
              </div>
        }
      </div>

      <div className="d-flex justify-content-center p-2">
        <div className="container">
          <div className="row border-bottom">
            <h3> Deletar Profissional </h3>
            
            <form>
            <div className="form-group">
                <label className="form-label" htmlFor="name">Nome</label>
                <input type="text" id="name" name="name" className="form-control" value={professional.name} readOnly />
              </div>
              <div className="form-group">
                    <label className="form-label" htmlFor="specialty">Especialidade</label>
                    <input type="text" id="specialty" name="specialty" className="form-control" value={professional.specialty} readOnly />
                </div>
              <div className="form-group">
                    <label className="form-label" htmlFor="contact">Contato</label>
                    <input type="text" id="contact" name="contact" className="form-control" value={professional.contact} readOnly />
                </div>
              <div className="form-group">
                <label className="form-label" htmlFor="phone_number">Telefone</label>
                <input type="text" id="phone_number" name="phone_number" className="form-control" value={professional.phone_number} readOnly />
              </div>
              <div className="form-group">
                <label className="form-label" htmlFor="status">Status</label>
                <select className="form-select" id="status" name="status" value={professional.status} readOnly>
                  {optionsStatus.map(option => (
                    <option key={option.value} value={option.value}>
                      {option.text}
                    </option>
                  ))}
                </select>
              </div>

              <div className="form-group">
                <label className="form-label" htmlFor="created_at">Data de Criação</label>
                <input type="text" id="created_at" name="created_at" className="form-control" value={professional.created_at} readOnly />
              </div>

              <div className="form-group p-2">
                <button 
                  className="btn btn-outline-danger" 
                  type="button" 
                  onClick={handleDeleteProfessional} 
                  disabled={isDeleted} // Desabilita o botão após deleção
                >
                    Deletar
                </button>
                <Link className="btn btn-outline-info" href="/admin/professionals">Voltar</Link>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
}
