import MenuAdmin from '@/components/MenuAdmin'
import NavAdmin from '@/components/NavAdmin'
import Head from 'next/head'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
export default function admin() {
  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div >
        <NavAdmin style={styles.container} className="custom-home"/>
        <MenuAdmin />
      </div>
  
      <div className="d-flex justify-content-center p-2">
        <div className="container">
          <div className="row border-bottom">
              <h3>Bem vindo!
              Ao Sistema de Base de Conhecimentos</h3>
          </div>
         
        </div>
      </div>  
  </>
  )
}


